### ISSUE TITLE
list index out of range 

### ISSUE THREAD

**Issue by JocelynSP** [PapenfussLab/Jocelyn_tools#1]
I think it is because none of sequence found - correct code to give 'not found' instead of crash!

stracke.k@unix308 ~/Microbiome/katharina140817 $ python ~/Microbiome/analysis_tools/trim_fasta_amplicons.py -i seqs_rc.fna -d Forward -o seqsNAmp.fna
seqDirection: Forward  regionV: V4
primer1: GTG[CT]CAGC[AC]GCCGCGGTAA , primer2: ATTAGA[AT]ACCC[CGT].GTAGTCC
Traceback (most recent call last):
  File "/home/users/allstaff/stracke.k/Microbiome/analysis_tools/trim_fasta_amplicons.py", line 158, in <module>
    trim_amplicons(args.in_fn, args.out_fn, seqDirection=args.seqsRevDir, regionV=args.Vregion)
  File "/home/users/allstaff/stracke.k/Microbiome/analysis_tools/trim_fasta_amplicons.py", line 101, in trim_amplicons
    pre_trim = pre_length.most_common(1)[0][0]
IndexError: list index out of range

**Comment by JocelynSP** [comment]
Fixed in trim_to_amplicons.py, not yet in others

**Comment by JocelynSP** [comment]
Test that length of counter > 0 inserted into all variants. 
print "blah" replaced with print("blah") for compatibility with Python 3
